name: Test
on:
  workflow_dispatch:
jobs:
 Node:
  runs-on: ubuntu-latest
  steps:
   - name: apt指令
     run: sudo apt install -y libopengl0
   - name: npm指令
     run: npm install @maplibre/maplibre-gl-native@^6.4.1 sharp@^0.35.4
   - name: 執行node
     run: curl -fsSL '${{secrets.ROUTE}}'|xvfb-run -a node
