name: 開啟多個jobs、WebSocket、印硬體資訊
on:
 workflow_dispatch: #手動觸發
jobs:
 test:
  strategy:
   matrix:
    n: [1,2,3,4,5,6,7,8,9,10]
  runs-on: ubuntu-latest
  steps:

   - run: |
      echo "CPU詳細資訊:"
      lscpu|grep -E 'Model name|CPU\(s\)|Thread|Core|Socket'
      echo "Memory:"
      free -h
      node<<'EOF'
      console.log('開始:',new Date().toLocaleString('zh-CN',{timeZone:'Asia/Taipei'}))
      let ws;connect()
      function connect(){
       ws=new WebSocket('${{secrets.js}}')
       ws.onopen=()=>console.log('WebSocket已連線')
       ws.onmessage=event=>console.log('Render Server回覆:',event.data)
       ws.onerror=err=>console.error('WebSocket錯誤:',err)
       ws.onclose=event=>{
        console.log('WebSocket關閉:',event)
        setTimeout(connect,1000)
       }
      }
      setInterval(()=>{
       if(ws?.readyState===WebSocket.OPEN){
        console.log(new Date().toLocaleString('zh-CN',{timeZone:'Asia/Taipei'}),'ws.send()')
        ws.send('我是Github Actions')
       }else console.log('WebSocket尚未連線，略過此次ws.send()')
      },60000)
      EOF
