name: Node Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Node.js
        run: |
          node -e "console.log('route from Node.js!')"
          node -e "console.log(new Date().toISOString())"
